export const SET_INITIAL_LOADING = 'SET_INITIAL_LOADING';
export const SET_SHOULD_LOAD = 'SET_SHOULD_LOAD';
export const SET_CURR_PAGE = 'SET_CURR_PAGE';
export const SET_COUNTRY_CODE = 'SET_COUNTRY_CODE';
export const SET_NEWS_CATEGORY = 'SET_NEWS_CATEGORY';
export const SET_NEWS_ARTICLES = 'SET_NEWS_ARTICLES';
export const SET_END_OF_ARTICLE = 'SET_END_OF_ARTICLE';
export const SET_ERROR_FOUND = 'SET_ERROR_FOUND';
export const COUNTRY_CHANGE = 'COUNTRY_CHANGE';
export const CATEGORY_CHANGE = 'CATEGORY_CHANGE';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_REFRESH = 'AUTH_REFRESH';

export const FLIP_DARK_MODE = 'FLIP_DARK_MODE';
