export const SET_INITIAL_LOADING = 'SET_INITIAL_LOADING';
export const SET_SHOULD_LOAD = 'SET_SHOULD_LOAD';
export const SET_CURR_PAGE = 'SET_CURR_PAGE';
export const SET_COUNTRY_CODE = 'SET_COUNTRY_CODE';
export const SET_NEWS_CATEGORY = 'SET_NEWS_CATEGORY';
export const SET_NEWS_ARTICLES = 'SET_NEWS_ARTICLES';
export const SET_END_OF_ARTICLE = 'SET_END_OF_ARTICLE';
export const SET_ERROR_FOUND = 'SET_ERROR_FOUND';
